name: "Terraform LocalStack"
description: "Terraform LocalStack"
icon: "check"
color: "purple"

runs:
  using: "composite"
  steps:

    - shell: bash
      run: |
        export TERM=xterm
        export TPUT=$(tput setaf 6)

        echo "${TPUT}Delete local provider.tf"
        touch provider.tf && rm provider.tf

        echo "${TPUT}Download LocalStack provider.tf"
        wget https://github.com/ShubhamTatvamasi/terraform-localstack-action/raw/master/provider.tf

        echo "${TPUT}Start LocalStack"
        docker run -d -p 4566:4566 -p 4571:4571 localstack/localstack

        echo "${TPUT}Initialize Terraform"
        terraform init

        echo "${TPUT}Validate files"
        terraform validate

        echo "${TPUT}Plan Apply"
        terraform plan -out apply.tfplan

        echo "${TPUT}Apply"
        terraform apply -auto-approve "apply.tfplan"

        echo "${TPUT}Show"
        terraform show

        echo "${TPUT}Plan Destroy"
        terraform plan -destroy -out destroy.tfplan

        echo "${TPUT}Destroy"
        terraform apply -auto-approve "destroy.tfplan"
