name: "Terraform LocalStack"
description: "Terraform LocalStack"
icon: "check"
color: "purple"

runs:
  using: "composite"
  steps:

    - shell: bash
      run: |
        echo "$(tput setaf 6)Delete local provider.tf"
        touch provider.tf && rm provider.tf

        echo "$(tput setaf 6)Download LocalStack provider.tf"
        wget https://github.com/ShubhamTatvamasi/terraform-localstack-action/raw/master/provider.tf

        echo "$(tput setaf 6)Start LocalStack"
        docker run -d -p 4566:4566 -p 4571:4571 localstack/localstack

        echo "$(tput setaf 6)Initialize Terraform"
        terraform init

        echo "$(tput setaf 6)Validate files"
        terraform validate

        echo "$(tput setaf 6)Plan Apply"
        terraform plan -out apply.tfplan

        ehco "$(tput setaf 6)Apply"
        terraform apply -auto-approve "apply.tfplan"

        echo "$(tput setaf 6)Show"
        terraform show

        echo "$(tput setaf 6)Plan Destroy"
        terraform plan -destroy -out destroy.tfplan

        echo "$(tput setaf 6)Destroy"
        terraform apply -auto-approve "destroy.tfplan"
